name: Daily Animalia News

on:
  schedule:
    - cron: '0 0 * * *'  # JSTの毎朝7:00（UTCの22:00）に実行
  workflow_dispatch:  # 手動実行ボタンも表示されるようにする

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Python をセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 依存ライブラリをインストール
        run: |
          python -m pip install --upgrade pip
          pip install openai requests

      - name: スクリプトを実行
        run: python main.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          WORDPRESS_USER: ${{ secrets.WORDPRESS_USER }}
          WORDPRESS_APP_PASSWORD: ${{ secrets.WORDPRESS_APP_PASSWORD }}
          WORDPRESS_URL: ${{ secrets.WORDPRESS_URL }}
